/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VGLD } from "./VGLD";
export * as factories from "./factories";
export { VGLD__factory } from "./factories/VGLD__factory";
