/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Forwarder } from "./Forwarder";
export type { VGLD } from "./VGLD";
export * as factories from "./factories";
export { Forwarder__factory } from "./factories/Forwarder__factory";
export { VGLD__factory } from "./factories/VGLD__factory";
